import { jsPDF } from "jspdf";
import autoTable from "jspdf-autotable";
import { format } from "date-fns";
import { fr, enUS } from "date-fns/locale";

const PRIMARY_COLOR: [number, number, number] = [10, 10, 10];
const ACCENT_COLOR: [number, number, number] = [168, 85, 247]; // Primary purple

export const exportDueDiligenceReport = (tasks: any[], listingName: string, t: any, lang: string) => {
  const doc = new jsPDF();
  const dateLocale = lang === 'fr' ? fr : enUS;
  
  // Header
  doc.setFillColor(...PRIMARY_COLOR);
  doc.rect(0, 0, 210, 40, "F");
  
  doc.setTextColor(255, 255, 255);
  doc.setFontSize(20);
  doc.setFont("helvetica", "bold");
  doc.text(lang === 'fr' ? "RAPPORT D'AUDIT & DUE DILIGENCE" : "DUE DILIGENCE AUDIT REPORT", 15, 20);
  
  doc.setFontSize(10);
  doc.setFont("helvetica", "normal");
  doc.text(`Projet / Dossier : ${listingName}`, 15, 30);
  
  // Body
  doc.setTextColor(0, 0, 0);
  doc.setFontSize(14);
  doc.setFont("helvetica", "bold");
  doc.text(lang === 'fr' ? "État d'avancement des tâches" : "Task Progress Status", 15, 55);

  const tableData = tasks.map(task => [
    task.category.toUpperCase(),
    task.title,
    task.status === 'completed' ? (lang === 'fr' ? 'Validé' : 'Completed') : 
    task.status === 'in_progress' ? (lang === 'fr' ? 'En cours' : 'In Progress') : (lang === 'fr' ? 'En attente' : 'Pending'),
    task.completed_at ? format(new Date(task.completed_at), 'dd/MM/yyyy HH:mm') : '-'
  ]);

  autoTable(doc, {
    startY: 65,
    head: [[
      lang === 'fr' ? "Catégorie" : "Category", 
      lang === 'fr' ? "Tâche / Vérification" : "Task / Verification", 
      lang === 'fr' ? "Statut" : "Status", 
      lang === 'fr' ? "Date" : "Date"
    ]],
    body: tableData,
    theme: 'grid',
    headStyles: { fillColor: ACCENT_COLOR, textColor: 255 },
    styles: { font: 'helvetica', fontSize: 9 },
    columnStyles: { 
      0: { cellWidth: 35 }, 
      1: { cellWidth: 85 },
      2: { cellWidth: 30 },
      3: { cellWidth: 30 }
    }
  });

  const finalY = (doc as any).lastAutoTable.finalY || 65;
  
  doc.setFontSize(8);
  doc.setTextColor(100, 100, 100);
  doc.text(
    lang === 'fr' 
      ? "Ce document est un extrait horodaté du suivi d'audit réalisé sur la plateforme GlobeTrade."
      : "This document is a timestamped extract of the audit tracking performed on the GlobeTrade platform.",
    15, finalY + 15
  );

  doc.save(`Due_Diligence_Report_${listingName.replace(/[^a-zA-Z0-9]/g, '_')}.pdf`);
};

export const exportVDRAuditTrail = (logs: any[], listingName: string, t: any, lang: string) => {
  const doc = new jsPDF();
  const dateLocale = lang === 'fr' ? fr : enUS;
  
  // Header
  doc.setFillColor(...PRIMARY_COLOR);
  doc.rect(0, 0, 210, 40, "F");
  
  doc.setTextColor(255, 255, 255);
  doc.setFontSize(20);
  doc.setFont("helvetica", "bold");
  doc.text(lang === 'fr' ? "REGISTRE D'ACCÈS DATA ROOM (VDR)" : "DATA ROOM ACCESS LOG (VDR)", 15, 20);
  
  doc.setFontSize(10);
  doc.setFont("helvetica", "normal");
  doc.text(`Projet / Dossier : ${listingName}`, 15, 30);
  
  // Body
  doc.setTextColor(0, 0, 0);
  doc.setFontSize(14);
  doc.setFont("helvetica", "bold");
  doc.text(lang === 'fr' ? "Historique des consultations (Audit Trail)" : "Viewing History (Audit Trail)", 15, 55);

  const tableData = logs.map(log => [
    format(new Date(log.created_at), 'dd/MM/yyyy HH:mm:ss'),
    log.viewer?.full_name || (lang === 'fr' ? 'Utilisateur inconnu' : 'Unknown user'),
    log.document?.name || (lang === 'fr' ? 'Fichier inconnu' : 'Unknown file'),
    "Accès sécurisé (NDA)"
  ]);

  autoTable(doc, {
    startY: 65,
    head: [[
      lang === 'fr' ? "Date & Heure" : "Date & Time", 
      lang === 'fr' ? "Utilisateur" : "User", 
      lang === 'fr' ? "Document consulté" : "Document viewed", 
      lang === 'fr' ? "Niveau d'accès" : "Access level"
    ]],
    body: tableData,
    theme: 'grid',
    headStyles: { fillColor: ACCENT_COLOR, textColor: 255 },
    styles: { font: 'helvetica', fontSize: 9 },
  });

  const finalY = (doc as any).lastAutoTable.finalY || 65;
  
  doc.setFontSize(8);
  doc.setTextColor(100, 100, 100);
  doc.text(
    lang === 'fr' 
      ? "Ce registre (Audit Trail) garantit la traçabilité des accès aux documents confidentiels. Généré par GlobeTrade."
      : "This Audit Trail guarantees the traceability of access to confidential documents. Generated by GlobeTrade.",
    15, finalY + 15
  );

  doc.save(`VDR_Audit_Trail_${listingName.replace(/[^a-zA-Z0-9]/g, '_')}.pdf`);
};